- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/errors/unprocessable_entity.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- config/locales/en/errors.yml
- config/locales/en/service.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3891)
add initial translations for error pages and service details
- Tests and rubocop should be passing: `bundle exec rake`
- You should have run `NOCOVERAGE=true rake rswag` to ensure the swagger docs are …
> ap-3891: add translations

- .simplecov
- spec/spec_helper.rb
Move simplecov config and amend
Use centralized simplecov config. I like this
method, as used in apply, and it means that if
we use another testing framework like cucumber
we just have to `require 'simplecov'` in its
test setup helper.
see https://github.com/simplecov-ruby/simplecov#using-simplecov-for-centralized-config
I have also reduced minimum coverage for now to not block CI
pipeline
[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)
Describe what you did and why.
- Tests and rubocop should be passing: `bundle exec rake`
- The PR …
> Move and amend simplecov config

- db/schema.rb
Add db/schema.rb file
Had not been added before due to db:prepare not having
been called.
- Tests and rubocop should be passing: `bundle exec rake`
- You should have run `NOCOVERAGE=true rake rswag` to ensure the swagger docs are up-to-date
> Add db/schema.rb file

- Gemfile.lock
Update bundler and fix gailure with ruby install and bundle in GHA
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3834)
- Update bundler
```
bundle update --bundler
=> 2.4.7
```
- Explicitly update gem debug to fix
```
Downloading debug-1.7.1 revealed dependencies not in the API or the lockfile
(irb (>= 1.5.0), reline (>= 0.3.1)).
Either installing with `--full-index` or running `bundle update debug` should
fix the problem.
```
fix was
```
gem install debug
bundle update
git add Gemfile.lock
...
```
- There should be no unnecessary whitespace changes. These make diffs harder to read and …
> Update bundler and rewrite Gemfile.lock

- docker-compose.yml
Serve static files via docker compose for local build testing
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3834)
Without RAILS_SERVE_STATIC_FILES a production
like config on a local machine will not serve assets
from the /public folder. This is because
production instances expect to run on apache or nginx
(in our case) which will do this by default regardless.
We may not need to add this for an actual hosted environment
therefore, but if so, we can add it simply enough via deployment
pipeline, production config or the Dockerfile itself.
- There should be no unnecessary whitespace changes. …
> Fix docker compose run for assets

- .github/workflows/test-build-deploy.yml
- .helm/assure-hmrc-data/templates/_envs.tpl
Prevent builds of dependabot PRs
- Do not build potentially unsafe dependencies
- test key addition via edit command
Building dependencies gives potentially malicious
code access to github action secrets. It is therefore
not recommended by github themselves and disabled by default
(causing builds to fail).
See [blog on dependabot PRs](
https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/)
- The PR description …
> prevent unsafe dependabot build

- .github/actions/deploy_branch/action.yml
- .github/workflows/test-build-deploy.yml
- .helm/assure-hmrc-data/templates/_envs.tpl
- .helm/assure-hmrc-data/values/uat.yaml
Add UAT deployment
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3938)
Deploy to UAT namespace
You can see the named deployments in the UAT namespace as follows
```shell
kubectl get pods -n laa-assure-hmrc-data-uat
```
You can see the current database in use by a UAT branch pod as follows
```
kubectl exec -it <pod name> -- sh
/usr/src/app $ rails c
> ActiveRecord::Base.connection.execute("select current_database()").to_a
=> [{"current_database"=>"ap-3938-add-uat-deployment"}]
```
- …
> [AP-3938] Add UAT deployment

- .simplecov
- app/views/errors/too_many_requests.html.erb
- config/locales/en/errors.yml
- spec/helpers/pages_helper_spec.rb
- spec/requests/errors_controller_spec.rb
- spec/views/pages/home.html.erb_spec.rb
Add test coverage for error controllers
Get to 100% coverage by adding tests and exluding
empty or abstract classes that are not being used 
as yet.
Have also commented out pending tests for now but could delete
entirely.
- You should have checked that the commit messages say why the change …
> Add test coverage for error controllers

- .helm/assure-hmrc-data/templates/_envs.tpl
- .rubocop.yml
- config/application.rb
Add Active Record encryption config and secrets
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3842)
Setup up active record encryption secrets so we
can encrypt user.auth_subject_id. This is used to
authenticate against azure ad.
we may also want encrypt email address at some point
for similar reasons.
NOTE: I have added k8s secrets to all environments now. different for each
- You should have …
> AP-3842: add AR encryption secrets keys

- .github/actions/deploy/action.yml
- .github/actions/deploy_branch/action.yml
Use reusable authenticate to cluster action
Added to [laa-reusable-github-actions](https://github.com/ministryofjustice/laa-reusable-github-actions)
To avoid repetition of logic. We pin it to a specific commit sha for immutability and, to a lesser extent, security (see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions for more)
- You should have looked at the diff …
> Use resuable authenticate to cluster action

- Gemfile.lock
Bump rack-test 2.0.2 to 2.1.0
This came out of a snyk PR supposedly
related to [SNYK-RUBY-RACK-1061917](https://security.snyk.io/vuln/SNYK-RUBY-RACK-1061917)
> Bump rack-test 2.0.2 to 2.1.0

- package.json
Add `postcss@^8.4.19` dev dependency
handle build warning
```
warning "stylelint-config-gds > stylelint-config-standard-scss > stylelint-config-recommended-scss > postcss-scss@4.0.6" has unmet peer dependency "postcss@^8.4.19".
```
- You should have checked that the commit messages say why …
> Add unmet peer dependency postcss@^8.4.19

- .env.sample
- Gemfile
- Gemfile.lock
- config/application.rb
- config/initializers/hmrc_interface.rb
- lib/hmrc_interface.rb
- lib/hmrc_interface/client.rb
- lib/hmrc_interface/configuration.rb
- spec/lib/hmrc_interface/client_spec.rb
- spec/lib/hmrc_interface/configuration_spec.rb
- spec/lib/hmrc_interface_spec.rb
- spec/spec_helper.rb
Add HMRC interface client
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4056)
To encapsulate authentication calls to the HMRC interface. Also adds a custom initializer specifically 
for isolating the configuration for it.
- You should have checked that the commit messages say why …
> AP-4056: Add hmrc interface client

- .rubocop.yml
- .simplecov
- docs/development/testing.md
- lib/hmrc_interface.rb
- lib/hmrc_interface/connection.rb
- lib/hmrc_interface/error.rb
- lib/hmrc_interface/error_helper.rb
- lib/hmrc_interface/request/base.rb
- lib/hmrc_interface/request/result.rb
- lib/hmrc_interface/request/submission.rb
- lib/tasks/hmrc_interface_test.rake
- lib/tasks/smoke_test.rb
- spec/fixtures/files/hmrc_interface_successful_result_response_body.json
- spec/lib/hmrc_interface/connection_spec.rb
- spec/lib/hmrc_interface/request/result_spec.rb
- spec/lib/hmrc_interface/request/submission_spec.rb
- spec/support/shared_contexts/hmrc_interface_stubs.rb
Enable request of result endpoint for a previous submission
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3994)
This `HmrcInterface::Request::Result`class will allow polling of the result from HMRC interface
for a given, previously queried, submission.
- You should have checked that …
> AP-3994: add hmrc interface result requests

- .helm/assure-hmrc-data/values/production.yaml
- .helm/assure-hmrc-data/values/staging.yaml
Remove old hosted zone ingress
To remove complexity and failed login paths due to redirect URL issues going from old custom domain to new.
It is not possible to sign in via the old staging and production
hosted zone `assure-hmrc-data.service.justice.gov.uk` without being
redirected back, by AzureAD, to the new hosted zone
`check-clients-details-using-hmrc-data.service.justice.gov.uk`. This
then causes an authentication failure.
see [this PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/12940) and [this one](https://github.com/ministryofjustice/cloud-platform-environments/pull/12939) for Cloud platform changes
- Github should not be reporting conflicts; you should …
> Remove old hosted zone domain

- .env.sample
- .helm/assure-hmrc-data/templates/_envs.tpl
- app/controllers/users/mock_azure_controller.rb
- config/application.rb
- db/seeds.rb
- docs/development/setup.md
- docs/development/testing.md
- spec/requests/users/mock_azure_controller_spec.rb
Only allow mock user to login using mock password
Allowing any user to login with the mock password
means they never get a first name and last name from azure
which results in empty text for the navigation item link.
It seems better IMO to have just one user for mock login in any
event as _current behaviour means anyone with the mock password can
login as anyone else._
I also moved the username (email) to the secrets for additional
security.
`MOCK_AZURE_USERNAME` env var has been added to UAT application secrets as part of this! I have changed the username from the one previously seeded so you will need to check the secrets to get it.
- Github should not be reporting conflicts; you should …
> Only allow mock user to login using mock password

- .gitignore
Add dump.rdb to .gitignore
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4043)
ignore local redis dump files as we do not want local generated data in the codebase
> AP-4043: gitignore dump.rdb

- config/initializers/extensions.rb
- lib/extensions/rails_module_extension.rb
- lib/rails_host.rb
- lib/rails_host_spec.rb
- spec/lib/rails_host_spec.rb
- spec/rails_helper.rb
- spec/support/test_helpers.rb
Add Rails host environment extension
Add shorthand methods to use for differentiating
what host environment we are on. This allows
us to add clear and concise conditionals
for functionality that should only be available
on a given host.
e.g. 
```ruby
if Rails.host.uat?
...
end
Rails.logger.info "[#{Rails.host.env}] doing something..."
```
- You should have looked at the diff against main and ensured that …
> Add Rails.host.env methods

- .github/actions/build_and_push/action.yml
- .github/actions/deploy/action.yml
- .github/actions/deploy_branch/action.yml
- .github/workflows/test-build-deploy.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4166)
Use short-lived ECR credentials to build and deploy images as per this guide https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-github-actions.
**TODO**
Move to a lifecycle policy for ECR images as we will no longer have the ability to run aws cli ecr commands/delete images with a script. See https://dsdmoj.atlassian.net/browse/AP-4178
- There should be no unnecessary whitespace changes. These make …
> ap-4166: use short-lived ecr credentials in test-build-deploy workflow

- app/models/concerns/hmrc_interface_resultable.rb
- app/services/submission_result_csv.rb
- config/initializers/extensions.rb
- lib/extensions/array_extension.rb
- spec/factories/submissions.rb
- spec/models/concerns/hmrc_interface_resultable_spec.rb
- spec/services/bulk_submission_result_writer_service_spec.rb
- spec/services/submission_result_csv_spec.rb
Extract data to required fields
Populates the following fields in the results CSV
~~- [x] “Tax Credit Annual Award Amount”~~
> AP-4181: extract clients income from employment to results

- app/models/concerns/hmrc_interface_resultable.rb
- app/services/submission_result_csv.rb
- lib/extensions/array_extension.rb
- spec/factories/submissions.rb
- spec/fixtures/files/results/hmrc_interface_successful_result_response_body_with_income_paye.json
- spec/models/concerns/hmrc_interface_resultable_spec.rb
- spec/services/bulk_submission_result_writer_service_spec.rb
- spec/services/submission_result_csv_spec.rb
Extract data to required fields
Populates the following fields in the results CSV
~~- [x] “Tax Credit Annual Award Amount”~~
~~- [x] “Client's Income from Employment”~~
- You should have checked that the commit messages say why the …
> AP-4181: Add "Clients NI contributions from employment" field to results

- app/models/concerns/hmrc_interface_resultable.rb
- app/services/submission_result_csv.rb
- spec/factories/submissions.rb
- spec/models/concerns/hmrc_interface_resultable_spec.rb
- spec/services/bulk_submission_result_writer_service_spec.rb
- spec/services/submission_result_csv_spec.rb
Extract data to required fields
Populates the following fields in the results CSV
~~- [x] “Tax Credit Annual Award Amount”~~
~~- [x] “Client's Income from Employment”~~
~~- [x] “Clients national insurance contributions from employment”~~
Inline with caseworker request this returns the
most recent/top payment amount and payment date
as a string, for example:
"2022-04-05: 1111.11"
- The PR description should say what you changed and …
> AP-4181: Add "Most recent payment" to results file

- spec/factories/submissions.rb
- spec/services/submission_result_csv_spec.rb
Remove redundant separate working and child taxt credit examples
Already covered by `hmrc_interface_resultable_spec.rb`
> AP-4181: remove redundant separate child and working tax credit examples

- app/models/concerns/hmrc_interface_resultable.rb
- app/services/submission_result_csv.rb
- spec/factories/submissions.rb
- spec/fixtures/files/results/hmrc_interface_successful_result_response_body_with_self_assessment_summary.json
- spec/models/concerns/hmrc_interface_resultable_spec.rb
- spec/services/bulk_submission_result_writer_service_spec.rb
- spec/services/submission_result_csv_spec.rb
Extract data to required fields
Populates the following fields in the results CSV
~~- [x] “Tax Credit Annual Award Amount”~~
~~- [x] “Client's Income from Employment”~~
~~- [x] “Clients national insurance contributions from employment”~~
~~- [x] “Most recent payment amount”~~
~~- [x] “Start and End dates for Employment”~~
Final field that case workers have asked for in an agreed format -
a multiline string with tax year and total income, as below
```
2019-20: 4487
2020-21: 5935
2021-22: 6722
```
- There should be no unnecessary whitespace …
> AP-4181: Add "Client's Income from Self Employment" to result file

- Gemfile
- Gemfile.lock
- app/models/bulk_submission.rb
- app/models/submission.rb
- db/migrate/20230618211606_add_discarded_at_to_bulk_submissions.rb
- db/migrate/20230618211622_add_discarded_at_to_submissions.rb
- db/schema.rb
- spec/models/bulk_submission_spec.rb
- spec/models/submission_spec.rb
- spec/support/shared_examples/discardable_examples.rb
Add soft deletion capability to bulk submission and submission data
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4171)
We should "hide" cancelled or removed bulk submissions from the list of
"checked details" but retain record data for auditing purposes.
I have used the [discard gem](https://rubygems.org/gems/discard/versions/1.2.1) because:
- it follows Apply's pattern
- is simple and robust implementation of a common pattern
- The PR description should say what you changed and …
> AP-4171: Add soft deletion capability to bulk submission and submission models

- config/initializers/hmrc_interface.rb
- lib/hmrc_interface/client.rb
- lib/hmrc_interface/configuration.rb
- spec/lib/hmrc_interface/client_spec.rb
- spec/lib/hmrc_interface/configuration_spec.rb
- spec/lib/hmrc_interface/request/result_spec.rb
- spec/lib/hmrc_interface/request/submission_spec.rb
Request scope specific doorkeeper tokens
[related PR for apply](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/5386)
Doorkeeper is used by HMRC interface to authenticate
requests. It is currently locked at doorkeeper 5.5.4 because
the handling of scopes changed in 5.6+.
However, we can request a token for specific scopes in
the current version 5.5.4 without breakages. ~~NEEDS TESTING~~ ✅ .
Once HMRC interface API is updated to use doorkeeper 5.6.6
(latest security patch), Assure app will continue to work
transparently.
Note: you can only request and successfully receive tokens
for scopes for which your application has been registered
with doorkeeper on HMRC Interface
- …
> Specify doorkeeper scopes which we want access to

- app/controllers/bulk_submissions_controller.rb
- app/views/bulk_submissions/index.html.erb
- app/workers/bulk_submissions_worker.rb
- app/workers/purge_sensitive_data_worker.rb
- spec/factories/bulk_submissions.rb
- spec/requests/bulk_submissions_controller_spec.rb
- spec/workers/bulk_submissions_worker_spec.rb
- spec/workers/purge_sensitive_data_worker_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4171)
Soft delete bulk submissions from index page, rather than destroy. This is
so we can retain the data for auditing purposes. Therefore both "Cancel", of pending,
and "Remove", of ready, bulk submissions should discard/soft-delete them. 
It follows, that if a bulk submission is discarded it should not be visible on the "Check details"
page and should not be processed, if it has not been already.
- The PR description should say what …
> AP-4171: enable soft-delete for bulk submissions

- app/views/bulk_submissions/index.html.erb
- spec/factories/bulk_submissions.rb
- spec/system/bulk_submission_index_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4165)
Added govuk styled buttons for Remove and Cancel
Added a Remove button for exhausted bulk_subissions
**TODO**
Add confirmations to the Remove and Cancel buttons (see https://dsdmoj.atlassian.net/browse/AP-4224).
- You should have …
> ap-4165: add govuk button styling to cancel and remove buttons

- app/controllers/bulk_submissions_controller.rb
- app/views/bulk_submissions/index.html.erb
- app/views/bulk_submissions/show.html.erb
- config/locales/en/views/bulk_submissions.yml
- config/routes.rb
- spec/system/bulk_submission_index_spec.rb
- spec/system/bulk_submission_show_spec.rb
Add a bulk submission show page and use for view cancel and remove
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4219)
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4224)
This allows cancel and remove to be links, not buttons, and
to take users to the show page with a confirmation for deletion.
- You should have looked at the diff against main and ensured that nothing unexpected is …
> AP-4129/4224: Add a confirmation mechanism for cancel and remove

- app/views/layouts/application.html.erb
- config/initializers/content_security_policy.rb
Add Content security policy
[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)
Security hardening. Issue raised by Zap security report.
- Initialize default rail content security policy in report only mode
- Add nonce to the single inline script in application.html.erb
- You should …
> Add content security policy

- config/initializers/content_security_policy.rb
Remove `https` from script-src CSP policy directive
[CSP-evaluator](https://csp-evaluator.withgoogle.com/) considers it
to be unsafe because:
> https: URI in script-src allows the execution of unsafe scripts.
Local and UAT testing reveals no negative consequences (CSP reports) from removing this.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your …
> Remove `https` from script-src CSP policy directive

- config/initializers/content_security_policy.rb
Enable content security policy
Improve site security using CSP headers.Testing reveals
no negative impact from the policy directives.
> Enable content security policy

- config/initializers/session_store.rb
Set secure flag on the applications session cookie so that the cookie cannot be accessed via unencrypted connections.
> Make session cookie store secure

- package.json
Enable minification in the CSS & JS build process
CSS => 30KB smaller when compiled
JS    => 90KB smaller when compiled
> Make FE assets performant

- .env.sample
- app/services/malware_scanner.rb
- config/application.rb
Remove use of LOCAL_CLAMAV
The bin/install_clamav_on_mac was altered to configure clamav
to use TCP meaning local clamav should work in the same way
as production clamav client - it will work using the
`clamd.container.conf` setting.
Therefore we do not need the LOCAL_CLAMAV config option and command
that it causes the app to use - `--fdpass` (for improved speed?!).
```
--fdpass
Pass the file descriptor permissions to clamd. This is useful if clamd is
running as a different user as it is faster than streaming the file to clamd.
Only available if connected to clamd via local(unix) socket.
```
- There …
> Remove use of LOCAL_CLAMAV

- docs/development/deployment.md
Update documentation regarding short lived credentials
Until we understand we how can move to short lived credentials for s3 and other
AWS services this just updates the documentation to warn of impending EoL
for long lived credentials.
- You should have checked that the commit messages say …
> Update documentation regarding short lived credentials

- .helm/assure-hmrc-data/templates/_envs.tpl
- .helm/assure-hmrc-data/templates/deployment-web.yaml
- .helm/assure-hmrc-data/templates/deployment-worker.yaml
- .helm/assure-hmrc-data/values/production.yaml
- .helm/assure-hmrc-data/values/staging.yaml
- .helm/assure-hmrc-data/values/uat.yaml
- config/storage.yml
Add IRSA service account and use instead of long lived credentials
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4288)
Switch to using IRSA policy for s3 bucket access.
Following instructions from [cloud-platform](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/accessing-aws-apis-and-resources-from-your-namespace.html#using-irsa-in-your-namespace) to
provide IAM role permissions to web and worker container pods.
See cloud-platform-environments irsa merged PRs
- https://github.com/ministryofjustice/cloud-platform-environments/pull/14282
- https://github.com/ministryofjustice/cloud-platform-environments/pull/14279
- https://github.com/ministryofjustice/cloud-platform-environments/pull/14194
- Tests and …
> AP-4288: Replace S3 long lived credentials with short lived IRSA service account 

- Dockerfile
Bump ruby alpine from 3.17 to [3.18](https://www.alpinelinux.org/posts/Alpine-3.18.0-released.html)
This aim to address the security vulnerable in golang
> Bump ruby alpine from 3.17 to 3.18

- .github/workflows/test-build-deploy.yml
Update ClamAV install step in the test pipeline.  
The mirror had updated and the clamav package could not be located
Running `sudo apg-get update` first ensures the mirror will be updated and the package found
> Update Clamav install

- Gemfile.lock
Reverts ministryofjustice/laa-assure-hmrc-data#524
Reverting as [rspec failing](https://github.com/ministryofjustice/laa-assure-hmrc-data/actions/runs/6170809277/job/16748003665#step:12:1050), therefore blocking build and release.
> Revert "build(deps): bump jsbundling-rails from 1.1.2 to 1.2.0"

- .github/workflows/test-build-deploy.yml
Allow manual triggering of CI/CD pipeline
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4456)
Allow manual triggering of the CI/CD pipeline so that
amended kubernetes secrets can be picked up.
See [workflow_dispatch](https://docs.github.com/en/github-ae@latest/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) for details
- You should have looked at the diff against main …
> AP-4456: Add `on: workflow_dispatch` triggering event

- Gemfile.lock
After a recent OSX update the platform list has updated when bundle install is run locally
- You should have checked that the commit …
> Chore: Update OS list in Gemfile.lock

- .github/actions/build_and_push/action.yml
- .github/actions/deploy/action.yml
- .github/actions/deploy_branch/action.yml
- .github/actions/get_release_name/action.yml
- .github/workflows/test-build-deploy.yml
There are a number of alerts that the current, v3, actions use an outdated node version.  This PR bumps all standard actions to v4 to try and remove the alerts
- You should have looked at the diff against main and ensured that nothing unexpected is …
> Chore: Update github action versions

- Gemfile
- Gemfile.lock
The gem has been update to 3.0.0 and started a deprecation process to replace dotenv-rails with a single-use dotenv gem
closes #876 
- …
> Fix: update DotEnv

- .helm/assure-hmrc-data/templates/deployment-web.yaml
- .helm/assure-hmrc-data/templates/deployment-worker.yaml
Following a recent cluster upgrade, the cluster was adding these values to deploys and outputting a warning that they should be explicitly set.
This explicitly sets the required securityContext values in all pods to make deploys quieter and allow better surfacing of actual errors
- The PR description should say what you changed and why, …
> Fix: Update k8s securityContext

- Gemfile
- Gemfile.lock
These have been in the application since the initial commit and I suspect that it was part of the original DFE template
They introduce a lot of dependencies so removing them will make a significant reduction to our dependency tree 🎉 
I have discussed with Joel and we are content that this will not impact the service, the gems are only in the development group so the removal will not affect the deployed service
>[!NOTE]
> I have logged in the the UAT environment and tested a variety of the test uploads and they have all completed successfully
- The standards in the [Git Workflow document on …
> Chore: Remove syntax_tree gems

- .github/workflows/clean-gh-actions-cache.yml
Add github workflow to clean Actions cache of closed PRs.
- You should have checked that the commit messages say why the change was …
> Chore: Cleanup GitHub Actions cache

- Gemfile.lock
The bundler dependabot passed tests but failed when building and deploying after merge.
There was an issue with the version of nokogiri not being available. This PR updates the platforms to match the working Apply deploy that included this nokogiri update
This PLATFORM list matches the platforms on Apply and should allow the build and deploy
It was updated using 
```sh
bundle lock --add-platform ruby
bundle lock --remove-platform x86_64-linux
``` …
> Fix: Update gemfile platforms

- app/controllers/status_controller.rb
- spec/requests/status_controller_spec.rb
Amend /healthcheck endpoint to use database_exists?
[Identified while working on](https://dsdmoj.atlassian.net/browse/AP-5668)
Inline with hmrc-interface app, at least, and best
practice since rails 7.2 as `active?` may be false
due to lazy loaded connections.
- The PR description should say what you changed and why, with a link to the …
> Chore: Amend /healthcheck endpoint to use database_exists?

- .github/dependabot.yml
This was designed to ignore all Rails updates above 7, now we have moved to Rails 8 this would cause
Rails to not update again
- You …
> Fix: Update dependabot after Rails upgrade

- config/puma.rb
Chore: Remove worker_timeout from puma config
[Came out of story](https://dsdmoj.atlassian.net/browse/AP-5668)
Added in intial commit but it is unclear why. It is not used in
Apply and and its default of 60 seconds should suffice.
- You should have …
> Chore: Remove worker_timeout from puma config

- .github/workflows/test-build-deploy.yml
In December 2024 we saw a dependabot update where the tests passed but, when the PPR was merged, the build step failed because of a mis-match with the versions used.  Moving the conditional from the build step to the deploy-uat step should ensure that we test a proper build of the dependabot changes but do not deploy it unless needed
- …
> Chore: Add build steps for dependabot PRs

- .helm/assure-hmrc-data/values/staging.yaml
- .helm/assure-hmrc-data/values/uat.yaml
Test the upgraded nginx modsec controller on non-prod environments.
To mitigate probelms on 15/04/2025 when they switch over.
From Cloud-platform:
```txt
We have deployed a non-prod modsec ingress controller to the cluster with the latest nginx and modsec rules (and upped the PCRE limit to tackle some of the errors you might have experienced with the recent failed upgrade).
You can test your existing ingress controller workloads by moving over your non prod workloads to the new non prod modsec controller and checking for any issues before the 15th. Please let us know what issues you hit asap.
To move your workloads over you just need to update your ingress className  from modsec => modsec-non-prod.
````
- Tests and linters should be passing: …
>  Test: turn on modsec-non-prod for UAT and staging

- .helm/assure-hmrc-data/values/staging.yaml
Increase SecPcreMatchLimit and SecPcreMatchLimitRecursion
[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)
To prevent PCRE limits on login against azureAd entraid from failing. 
currently modsec-non-prod is causing 403 errors on the entraid callback
- The PR description should say what you changed and why, with a link to the …
> AP-5915: Fix - Increase SecPcreMatchLimit and SecPcreMatchLimitRecursion

- .github/workflows/test-build-deploy.yml
This was added to try and prevent build failures - see #1485 - when merging dependabot PRs but caused more pain as *every* PR then failed to build and had to be manually built and deployed anyway
Reverting to prevent pain, although we will need to consider how often these will fail to build and
deploy when we switch to GA full time on all repos!
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts …
> Chore: revert build step

- .github/actions/deploy_branch/action.yml
Allow custom errors on main branch only
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6241)
The custom error config map, service and pod/deployment
are shared by all branches in the UAT namespace. They need to
be deployed to UAT on merge to main or their existing components are 
destroyed, but they should only be deployed against main.
```
env:
...
RELEASE_NAME: ap-6241-allow-custom-errors-on
is_main variable value is: false <-- TESTING
```
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) should be …
> AP-6241: Allow custom errors on main branch only
