.github/dependabot.yml, Gemfile, README.md, app/controllers/errors_controller.rb, bin/bundle, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/filter_parameter_logging.rb, config/puma.rb, config/routes.rb, config/storage.yml, spec/helpers/pages_helper_spec.rb, spec/rails_helper.rb, spec/requests/pages_spec.rb, spec/spec_helper.rb, spec/views/pages/home.html.erb_spec.rb
Auto correct/format linting violations
- Autocorrect rubocop violations using `rubocop`
- Auto format md, yml, rb files using `prettier`
=> Autocorrect lint violations

Gemfile, Gemfile.lock, spec/spec_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3847)
implement code coverage with simplecov
Configure simplecov to require 100% code coverage
Add highline gem to format simplecov output
=> ap-3487: implement code coverage withsimplecov

.github/pull_request_template.md
Amend pull request template
To reflect actual requirements currently
- Tests and rubocop should be passing: `bundle exec rake`
- You should have run `NOCOVERAGE=true rake rswag` to ensure the swagger docs are up-to-date
=> Amend pull_request_template

Gemfile, Gemfile.lock, config/i18n-tasks.yml, config/locales/en/errors.yml, config/locales/en/service.yml, spec/i18n_spec.rb
Add i18n-tasks with config and specs
Since we are using translations we should
test for, at least, no missing keys and unused
keys. keys being normalized and "consistent" interpolation
test has been added too for now.
- You should have checked that the commit messages say why the change was …
=> Add i18n-tasks gem and configure

Gemfile
Move gem in order
rubocop linting
=> Move I18n-tasks gem

.erb-lint.yml, Gemfile, Gemfile.lock, app/views/layouts/application.html.erb, lib/tasks/erblint.rake
Enable linting of erb files with erb_lint gem
=> Enable linting of erb files with erb_lint gem

.github/workflows/test-build-deploy.yml, docs/development/deployment.md
Add a github action workflow for CI and CD for test and lint (only)
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3834)
Implement continuous integration
=> [AP-3834] Add github action workflow for test and lint

app/controllers/status_controller.rb, config/application.rb, config/routes.rb, spec/requests/status_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3907)
Added /ping and /healthcheck and /status endpoints
=> ap-3907: add ping and healthcheck endpoints

Dockerfile
Fix dockerfile security vulnerability
Gemfile* creates potential attack vector to anyfile
named Gemfile[myinjectedfile].
=> Fix security hotspot

.helm/assure-hmrc-data/templates/_envs.tpl, .helm/assure-hmrc-data/templates/deployment-web.yaml
Extract secret_key_base from k8s application secret
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3835)
see [secret management](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4333306265/Secret+management)
- You should have checked that the commit messages say why the change …
=> [AP-3835] use kubernetes application secret

.helm/assure-hmrc-data/templates/_envs.tpl, Gemfile, Gemfile.lock, config/initializers/sentry.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3849)
-Added sentry-ruby and sentry-rails gems
-Added sentry.rb initiliazer
-Added sentry_dsn secret
=> ap-3849: Add sentry

.helm/assure-hmrc-data/templates/_envs.tpl
Remove test secret var reference
=> Remove test secret reference

.helm/assure-hmrc-data/templates/_envs.tpl
[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)
Describe what you did and why.
=> Use moved sentry_dsn secret

.helm/assure-hmrc-data/templates/ingress.yaml, .helm/assure-hmrc-data/values/staging.yaml
Add custom domain ingress for staging
production hosted-zone/domain generated and certificate
for staging subdomain created.
=> Add custom domain ingress for staging

.github/workflows/test-build-deploy.yml, .helm/assure-hmrc-data/values/production.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3820)
Add ability to deploy to production namespace.
=> ap-3820 amend github action workflow to allow deploy to production

.github/workflows/test-build-deploy.yml, Gemfile, docker-compose.yml
Store code coverage artifact for 7 days (90 days by default)
Make code coverage results available on the pipeline, see screenshot
=> Add coverage artifacts to gha

.github/workflows/brakeman-analysis.yml, .github/workflows/docker-image-scan.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3958)
- Added static analysis code scanning with brakeman
- Added docker image scanning with Snyk
=> ap-3958: add security scanning

.github/actions/deploy/action.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3836)
- Enable alllow listing of MOJ ip addresses
- Add allow list to assure-hmrc-data-application-output (staging and production namespaces only).
- Decode and read this secret (escaping commas) and use it to set ingress annotations
Describe what you did and why.
- You should have looked at the diff against main and ensured that nothing unexpected …
=> ap-3836: enable allow listing

.github/actions/delete_ecr_images/action.yml, .github/workflows/clean-up-ecr.yml, bin/delete_ecr_images
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3997)
Create github action to call Ruby script that identifies and deletes ECR images > 10 days old.
Create workflow to run this nightly at 2am.
=> ap-3997: Add github action and workflow to delete ECR images

docs/development/setup.md
The auth_provider attribute was missing from the instruction
=> Tweak setup instructions

.helm/assure-hmrc-data/templates/ingress.yaml, .helm/assure-hmrc-data/values/production.yaml, .helm/assure-hmrc-data/values/staging.yaml
New and additional custom domain name
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3975)
We want new domain and old domain. old may be
deleted eventually.
dependant on this PR https://github.com/ministryofjustice/cloud-platform-environments/pull/12586
- You should have checked that …
=> AP-3975: Add additional custom domain

Gemfile.lock
Add M1 dependencies to gemfile
=> Add M1 platform depenencies

app/models/bulk_submission.rb, app/models/submission.rb, app/validators/not_in_future_validator.rb, config/i18n-tasks.yml, config/locales/en/models/submissions.yml, db/migrate/20230427141829_create_submissions.rb, db/schema.rb, spec/factories/submissions.rb, spec/models/bulk_submission_spec.rb, spec/models/submission_spec.rb
Create database table and its model for "submissions"
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4056)
The submissions table and model will store request details
and their response from the hmrc interface. Taking input
from the uploaded file attached to the bulk_submission
object.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your …
=> AP-4056: Add submissions table and model

Gemfile.lock, app/views/layouts/application.html.erb, app/views/pages/landing.html.erb, config/locales/en/views/bulk_submissions.yml, config/locales/en/views/layouts.yml, config/locales/en/views/pages.yml, spec/requests/bulk_submissions_controller_spec.rb, spec/system/bulk_submission_index_spec.rb, spec/system/sign_in_spec.rb
HMRC design amendments
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4042)
Add content to landing page in line with [designs](https://www.figma.com/file/HrVZGjvgsCYqhLt5O7UHVI/HMRC-assurance-tool?node-id=232-13&t=2LuJZe18mpDCEjCM-0). 
- You should have checked that the commit …
=> AP-4042: HMRC design amendments

spec/system/bulk_submission_form_dropzone_spec.rb
Add system tests for validations to guard against regressions.
=> Add system test for validations

docs/development/sidekiq_flows.md
Readme format and content tweaks
Corrects some bad indentation and minor content changes
=> Formatting tweaks to sidekiq flow readme

spec/support/shared_examples/worker_examples.rb, spec/workers/bulk_submission_result_writer_worker_spec.rb, spec/workers/bulk_submission_status_worker_spec.rb, spec/workers/bulk_submission_worker_spec.rb, spec/workers/bulk_submissions_worker_spec.rb, spec/workers/hmrc_interface_bulk_submission_worker_spec.rb, spec/workers/hmrc_interface_result_worker_spec.rb, spec/workers/hmrc_interface_submission_worker_spec.rb
Fix typo in shared example name
My fat fingers!
=> Fix typo in shared example name

spec/lib/hmrc_interface/request/submission_spec.rb, spec/support/shared_contexts/hmrc_interface_stubs.rb, spec/system/bulk_submission_processing_spec.rb, spec/system/bulk_submission_result_file_generation_spec.rb
Add system tests for result file generation
Add overriding system tests to cover 3 primary scenarios
identified:
1. when client is employed
2. when client is self employed
3. when client receives working or child tax credit
- You …
=> AP-4181: Add system tests for mapped data output

.rubocop.yml, app/controllers/bulk_submission_forms_controller.rb, app/forms/bulk_submission_form.rb, app/forms/concerns/malware_scanning.rb, app/models/malware_scan_result.rb, app/services/malware_scanner.rb, config/locales/en/models/bulk_submissions.yml, spec/forms/bulk_submission_form_spec.rb, spec/requests/bulk_submission_forms_controller_spec.rb, spec/services/malware_scanner_spec.rb, spec/system/bulk_submission_form_dropzone_spec.rb
Store the user that attempted to upload the file for auditing purposes
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4158)
=> AP-4158: virus scanning audit user

app/controllers/bulk_submission_forms_controller.rb
[Came out of review on story](https://dsdmoj.atlassian.net/browse/AP-4158)
Use strong params for bulk submission ID
=> Refactor bulk submission form to use strong params only

app/workers/purge_sensitive_data_worker.rb, spec/workers/purge_sensitive_data_worker_spec.rb
Discard undiscarded bulk submissions that have been purged
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4197)
This will prevent them from being displayed on the index page
=> AP-4197: discard undiscarded bulk submissions that have been purged

config/locales/en/views/bulk_submissions.yml, spec/system/bulk_submission_index_spec.rb, spec/system/bulk_submission_show_spec.rb
Amend text for the cancel and remove buttons
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4219)
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4224)
Inline with content design tweaks
=> AP-4224: Amend text for cancel and remove buttons

app/controllers/bulk_submissions_controller.rb, app/views/bulk_submissions/index.html.erb, app/views/bulk_submissions/show.html.erb, config/application.rb, config/initializers/sidekiq.rb, config/routes.rb, spec/requests/bulk_submissions_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4168)
Log user downloading bulk submission results file
Configure log level to :info in development and production, :warn in test.
=> ap-4168: log user that downloads bulk submission results file

.github/workflows/test-build-deploy.yml, .helm/assure-hmrc-data/templates/deployment-web.yaml, docker-compose.yml
Bump hmpps-clamav to latest image version
Stay upto date with virus definitions
I have UAT tested upload of malware with it being successfully blocked
=> Bump hmpps-clamav to latest image version

.github/workflows/docker-image-scan.yml
This allows us to speed up testing of Snyk checks
=> Add manual button to snyk scan action

.rspec, spec/lib/hmrc_interface/client_spec.rb, spec/lib/hmrc_interface/connection_spec.rb, spec/lib/hmrc_interface/request/submission_spec.rb, spec/rails_helper.rb, spec/support/shared_contexts/hmrc_interface_stubs.rb
This should surface race conditions in the test suite
Opened as a test - first run (with `--seed 51610`) failed
=> Chore: Randomize RSpec

docs/development/setup.md
Update setup documentation:
- Add step to change mock azure env var
- Update name of value to take from azure
=> Docs: update setup documentation

.github/pull_request_template.md
Update pull request template to include git workflow
=> Docs: Update pull request template to include git workflow

.github/workflows/delete-uat-release.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4569)
Bump version number of delete uat github action to v1.1.0
- You should …
=> AP-4569: bump delete uat github action version

.github/dependabot.yml
Enable all stylelint* node packages to be updated together.
- You should have checked that the commit messages say why the change was …
=> Dependabot: group stylelint dependencies

.github/workflows/test-build-deploy.yml, .helm/assure-hmrc-data/templates/deployment-web.yaml, docker-compose.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3151)
Update hmpps clamav to track latest version
- You should have checked …
=> AP-3151: Update hmpps clamav to track latest version

.helm/assure-hmrc-data/templates/deployment-web.yaml, .helm/assure-hmrc-data/templates/deployment-worker.yaml
Add newly required securityContext values to reduce noise when deploying via circle ci
These were missed from the first PR
- You …
=> Fix: K8s warnings

.github/dependabot.yml
Enable all GOVUK* gems to be updated together.
=> Chore: Add GOVUK dependabot bundler group

.github/dependabot.yml
This duplicates the one in Apply that merges the js and css updates that always occur on the same day
- You should have checked that …
=> Chore: Add bundling group to Dependabot

package.json, yarn.lock
Bump `esbuild` from 0.24.2 to 0.25.0
Bump `prettier` from 3.4.2 to 3.5.0
- You should have checked that the commit messages say why …
=> Chore(deps): Bump the npm group with 2 updates

.github/workflows/test-build-deploy.yml, docker-compose.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5944)
Upgrade CI postgres from v14 to v17, keeping it inline with the server.
- …
=> Ap 5944 upgrade ci postgres v17

app/assets/stylesheets/_imports.scss, app/assets/stylesheets/application.sass.scss, app/assets/stylesheets/dropzone.scss, app/javascript/application.js
[Update Sass out the box functions](https://dsdmoj.atlassian.net/browse/AP-5954)
We’re replacing Sass `import` rule with the `use` and `forward` rules
- You should have looked at the diff against main and ensured that nothing unexpected is included …
=> AP-5954: Use Sass 'use' and 'forward' rules

.helm/assure-hmrc-data/values/production.yaml, .helm/assure-hmrc-data/values/staging.yaml
Take service offline
HMRC API has been shuttered
=> Incident: Take service offline

app/views/bulk_submission_forms/_form_fields.html.erb, app/views/layouts/application.html.erb
- Fix reference to opengraph image 
- Use double quotes consistently in HTML
- You should have checked that the commit messages say …
=> Chore: tidy up html

.helm/assure-hmrc-data/values/production.yaml, .helm/assure-hmrc-data/values/staging.yaml, .helm/assure-hmrc-data/values/uat.yaml
Correct end time for business hours
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6241)
It should *close* at 10pm, so the Last available minute is 21:59 
in the zone which is 20:59 UTC during BST. So hour 20 is allowed 
while hour 21 is not.
- The PR description should say what you changed and why, with a link to the JIRA …
=> AP-6241: correct end time for business hours

.github/dependabot.yml
Ignore npm based updates
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6260)
While Shai-Hulud supply chain attack its ongoing 
- You should have looked at the diff against main and ensured that nothing unexpected is included in your …
=> AP-6260: Ignore npm based updates
